/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksIndexRouteImport } from './routes/hooks/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as HooksUsePageLeaveRouteImport } from './routes/hooks/usePageLeave'
import { Route as HooksUseMobileRouteImport } from './routes/hooks/useMobile'
import { Route as ComponentsSwitchCaseRouteImport } from './routes/components/SwitchCase'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksIndexRoute = HooksIndexRouteImport.update({
  id: '/hooks/',
  path: '/hooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksUsePageLeaveRoute = HooksUsePageLeaveRouteImport.update({
  id: '/hooks/usePageLeave',
  path: '/hooks/usePageLeave',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksUseMobileRoute = HooksUseMobileRouteImport.update({
  id: '/hooks/useMobile',
  path: '/hooks/useMobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSwitchCaseRoute = ComponentsSwitchCaseRouteImport.update({
  id: '/components/SwitchCase',
  path: '/components/SwitchCase',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/SwitchCase': typeof ComponentsSwitchCaseRoute
  '/hooks/useMobile': typeof HooksUseMobileRoute
  '/hooks/usePageLeave': typeof HooksUsePageLeaveRoute
  '/components': typeof ComponentsIndexRoute
  '/hooks': typeof HooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/SwitchCase': typeof ComponentsSwitchCaseRoute
  '/hooks/useMobile': typeof HooksUseMobileRoute
  '/hooks/usePageLeave': typeof HooksUsePageLeaveRoute
  '/components': typeof ComponentsIndexRoute
  '/hooks': typeof HooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/SwitchCase': typeof ComponentsSwitchCaseRoute
  '/hooks/useMobile': typeof HooksUseMobileRoute
  '/hooks/usePageLeave': typeof HooksUsePageLeaveRoute
  '/components/': typeof ComponentsIndexRoute
  '/hooks/': typeof HooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/SwitchCase'
    | '/hooks/useMobile'
    | '/hooks/usePageLeave'
    | '/components'
    | '/hooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/SwitchCase'
    | '/hooks/useMobile'
    | '/hooks/usePageLeave'
    | '/components'
    | '/hooks'
  id:
    | '__root__'
    | '/'
    | '/components/SwitchCase'
    | '/hooks/useMobile'
    | '/hooks/usePageLeave'
    | '/components/'
    | '/hooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsSwitchCaseRoute: typeof ComponentsSwitchCaseRoute
  HooksUseMobileRoute: typeof HooksUseMobileRoute
  HooksUsePageLeaveRoute: typeof HooksUsePageLeaveRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  HooksIndexRoute: typeof HooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/': {
      id: '/hooks/'
      path: '/hooks'
      fullPath: '/hooks'
      preLoaderRoute: typeof HooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/usePageLeave': {
      id: '/hooks/usePageLeave'
      path: '/hooks/usePageLeave'
      fullPath: '/hooks/usePageLeave'
      preLoaderRoute: typeof HooksUsePageLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/useMobile': {
      id: '/hooks/useMobile'
      path: '/hooks/useMobile'
      fullPath: '/hooks/useMobile'
      preLoaderRoute: typeof HooksUseMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/SwitchCase': {
      id: '/components/SwitchCase'
      path: '/components/SwitchCase'
      fullPath: '/components/SwitchCase'
      preLoaderRoute: typeof ComponentsSwitchCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsSwitchCaseRoute: ComponentsSwitchCaseRoute,
  HooksUseMobileRoute: HooksUseMobileRoute,
  HooksUsePageLeaveRoute: HooksUsePageLeaveRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  HooksIndexRoute: HooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
