/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SwitchCaseRouteImport } from "./routes/switchCase";
import { Route as IndexRouteImport } from "./routes/index";

const SwitchCaseRoute = SwitchCaseRouteImport.update({
  id: "/switchCase",
  path: "/switchCase",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/switchCase": typeof SwitchCaseRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/switchCase": typeof SwitchCaseRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/switchCase": typeof SwitchCaseRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/switchCase";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/switchCase";
  id: "__root__" | "/" | "/switchCase";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SwitchCaseRoute: typeof SwitchCaseRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/switchCase": {
      id: "/switchCase";
      path: "/switchCase";
      fullPath: "/switchCase";
      preLoaderRoute: typeof SwitchCaseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SwitchCaseRoute: SwitchCaseRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
