/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksIndexRouteImport } from './routes/hooks/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as HooksHookNameRouteImport } from './routes/hooks/$hookName'
import { Route as ComponentsComponentNameRouteImport } from './routes/components/$componentName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksIndexRoute = HooksIndexRouteImport.update({
  id: '/hooks/',
  path: '/hooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksHookNameRoute = HooksHookNameRouteImport.update({
  id: '/hooks/$hookName',
  path: '/hooks/$hookName',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComponentNameRoute = ComponentsComponentNameRouteImport.update({
  id: '/components/$componentName',
  path: '/components/$componentName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/hooks/$hookName': typeof HooksHookNameRoute
  '/components': typeof ComponentsIndexRoute
  '/hooks': typeof HooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/hooks/$hookName': typeof HooksHookNameRoute
  '/components': typeof ComponentsIndexRoute
  '/hooks': typeof HooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/hooks/$hookName': typeof HooksHookNameRoute
  '/components/': typeof ComponentsIndexRoute
  '/hooks/': typeof HooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/$componentName'
    | '/hooks/$hookName'
    | '/components'
    | '/hooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/$componentName'
    | '/hooks/$hookName'
    | '/components'
    | '/hooks'
  id:
    | '__root__'
    | '/'
    | '/components/$componentName'
    | '/hooks/$hookName'
    | '/components/'
    | '/hooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsComponentNameRoute: typeof ComponentsComponentNameRoute
  HooksHookNameRoute: typeof HooksHookNameRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  HooksIndexRoute: typeof HooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/': {
      id: '/hooks/'
      path: '/hooks'
      fullPath: '/hooks'
      preLoaderRoute: typeof HooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/$hookName': {
      id: '/hooks/$hookName'
      path: '/hooks/$hookName'
      fullPath: '/hooks/$hookName'
      preLoaderRoute: typeof HooksHookNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$componentName': {
      id: '/components/$componentName'
      path: '/components/$componentName'
      fullPath: '/components/$componentName'
      preLoaderRoute: typeof ComponentsComponentNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsComponentNameRoute: ComponentsComponentNameRoute,
  HooksHookNameRoute: HooksHookNameRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  HooksIndexRoute: HooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
